#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Shubham Mishra | Registration: 24BCY10064
# Purpose: Generate a personalized open source philosophy statement
# Concepts: read for user input, string concatenation, file output, date command

echo "=================================="
echo "  OPEN SOURCE MANIFESTO GENERATOR"
echo "=================================="
echo ""
echo "Welcome! This script will help you compose your personal"
echo "open source philosophy statement."
echo ""
echo "Answer the three questions below:"
echo ""

# --- Read user input for three questions ---
# Question 1: Name an open-source tool used daily
read -p "1. Name one open-source tool you use every day: " TOOL

# Question 2: Define freedom in one word
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM

# Question 3: Something they would build and share freely
read -p "3. Name one thing you would build and share freely: " BUILD

echo ""

# --- Generate timestamp for the manifesto ---
DATE=$(date '+%d %B %Y')           # Date in format: 01 January 2024
TIME=$(date '+%H:%M:%S')           # Time in format: 14:30:45
USERNAME=$(whoami)                 # Get current user's name
HOSTNAME=$(hostname)               # Get system hostname

# --- Define output file name ---
OUTPUT="manifesto_${USERNAME}_$(date '+%Y%m%d').txt"

# --- Create the manifesto content using string concatenation ---
# The manifesto uses the user's answers to create a personalized statement

echo "Generating your manifesto..."
echo ""

# --- Write manifesto to file ---
cat > "$OUTPUT" << EOF
╔════════════════════════════════════════════════════════════════╗
║     PERSONAL OPEN SOURCE MANIFESTO                             ║
║                                                                ║
║     Author  : Shubham Mishra (24BCY10064)                     ║
║     Created : $DATE at $TIME                  ║
║     System  : $HOSTNAME                                        ║
║     User    : $USERNAME                                        ║
╚════════════════════════════════════════════════════════════════╝

MY PHILOSOPHY ON OPEN SOURCE

I write this manifesto on $DATE, as a developer who understands that
the tools we use shape the world we build.

Every day, I rely on $TOOL—a gift from the open source community.
This tool embodies the principle that knowledge should flow freely,
that problems deserve open solutions, and that the best ideas emerge
when we share them without barriers.

To me, $FREEDOM means more than just availability. It means the power
to understand, to modify, to improve, and to share improvements with
others. It means nobody owns the future—we all build it together.

The proprietary software industry wants us to believe that code must
be locked away to have value. Open source proves the opposite: when
we open our work to scrutiny, collaboration, and community feedback,
it becomes stronger, more secure, and ultimately more valuable.

If I could create something and share it freely with the world, it
would be $BUILD. Why? Because the world doesn't need another locked
box. It needs tools that respect the user, respect the developer, and
recognize that innovation happens at the intersection of many minds,
not behind the walls of a single corporation.

I believe that every piece of software I write—whether it's a small
script or a large application—is built on the shoulders of giants:
the Linux kernel, the GNU tools, the open protocols, the shared
libraries. I owe a debt to the community. The only way to repay it
is to give back.

This is my commitment:
  • I will write software that respects user freedom
  • I will share my code openly and invite collaboration
  • I will credit and acknowledge the open source projects I depend on
  • I will contribute back to the projects that help me
  • I will believe that opening the source code is an act of respect,
    not a weakness

The open source movement is not just a licensing model or a development
practice. It is a philosophical stance: that tools belong to humanity,
that knowledge should be free, and that together, we can build better.

═══════════════════════════════════════════════════════════════════

Generated by: Open Source Manifesto Generator
Script Author: Shubham Mishra (24BCY10064)
Course: Open Source Software (OSS NGMC)

This manifesto was created by the author through reflection on open
source values and is hereby placed in the public domain.
EOF

# --- Confirm file creation and display the manifesto ---
echo "✓ Manifesto created successfully!"
echo ""
echo "Saved to: $OUTPUT"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "YOUR MANIFESTO:"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# --- Display the created manifesto to the user ---
cat "$OUTPUT"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Thank you for reflecting on open source philosophy."
echo "Your manifesto has been saved and is ready to be part of your"
echo "Open Source Audit project."
echo "═══════════════════════════════════════════════════════════════"
